version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "pip install numpy==1.26.4"
      - "pip install py_stringmatching==0.4.5"
      - "pip install . "
      - "jupyter-book config sphinx docs/"
      - echo "Command run at 'pre_create_environment' step"
      - pwd

sphinx:
  configuration: docs/conf.py  # Path to your Sphinx conf.py

python:
   install:
   - requirements: docs/requirements.txt
  #  - method: pip
  #    path: .
  #    extra_requirements:
  #     - sphinx

# formats:
#   - pdf
#   - epub
