version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/"
      - echo "Command run at 'pre_create_environment' step"
      - pwd

python:
   install:
   - requirements: docs/requirements.txt
  #  - method: pip
  #    path: .
  #    extra_requirements:
  #     - sphinx

# sphinx:
#   builder: html
#   fail_on_warning: true

# formats:
#   - pdf
#   - epub
